### PR TITLE
Add Share Link

### PR DESCRIPTION
**Pull request by victorbrambati**
I see this Issues #28 then I implemented a share link transforming json in base64 for use in url.

### CODE REVIEW

**Comment by AykutSarac** [comment]
The link is extremely long, we should find a way to make it shorter. Best way is seems to be connect the link with URL shortener service and display the user shortened link. Thanks for your contribution, I'll keep it open for now!

**Comment by victorbrambati** [comment]
> The link is extremely long, we should find a way to make it shorter. Best way is seems to be connect the link with URL shortener service and display the user shortened link. Thanks for your contribution, I'll keep it open for now!

It is a good idea, but I searched for a lot shortner service and I didn't find a free service that fits this project. I thought of another way, for create a link minify the json and encode on base64 and for read the link beautify the json and decode the base64. It has cut by nearly half the size of link.

**Comment by AykutSarac** [comment]
Thanks for the PR. However we cannot implement it as there are conditions such as the file size could be very big and the link could be so long thus it'd lead to further issues. Instead I'm planning to connect it to a backend to save JSON & generate links, that way we could also implement website embeds as well.

Closing the PR, thanks for the insights!

**Comment by AykutSarac** [comment]
Thanks for your contribution, after making appropriate changes matching with the main branch I'm merging your PR!

**Pull request merged**
